services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    environment:
      - VUE_APP_API_URL=${VUE_APP_API_URL}
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
